baseurl = "/"
languageCode = "pt-br"
title = "Macetes Incríveis"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Fighting games/Rhythm Games/Shmups/Sei lá"
  cover = "images/cover.jpg"
  author = "lofi1048"
  authorlocation = "Rio de Janeiro, Brasil"
  authorwebsite = "http://twitter.com/lofi1048"
  bio= "Minha vítima, não me ganha"
  logo = "images/lofi.svg"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  # githubName = "fabricioanciaes"
  twitterName = "lofi1048"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "lofi1048"
